### ISSUE TITLE
settings to disable auto refresh entirely

### ISSUE THREAD

**Issue by ichylinux** [maedadev/redmine_backlogs#13]
we run redmine with a limited hardware spec.
enabling auto refresh makes a lot of requests and our server can't handle the traffic.

**Comment by ichylinux** [comment]
hi, @fuminori-ido-m 
can you review this?

**Comment by fuminori-ido-m** [comment]
Thank you for your update!  I understand that this feature and it is reasonable to disable in some cases (I saw a lot of access every second ...).

I do not see any issue on your update.  It looks already merged into master so that we can close this ticket!

**Comment by ichylinux** [comment]
thank you for your review!
